language: php
php:
  - '5.6'
install: composer install --no-interaction
script:
#    Run tests
  - ./vendor/bin/phpunit
branches:
  only: master
cache:
  directories:
  - vendor
  - $HOME/.cache/composer
